repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      types: [python]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
    -   id: isort
